# Generated by Django 4.2.7 on 2023-11-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('IT', 'BSIT'), ('CS', 'BSCS')], max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTQ', 'LGBTQ')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('studNo', models.IntegerField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('age', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.course')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.gender')),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='webapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(blank=True, max_length=50)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_end', models.TimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(choices=[('P', 'Passed'), ('C', 'Conditional'), ('F', 'Failed')], max_length=1)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.subject')),
            ],
        ),
    ]
