# Generated by Django 4.2.7 on 2023-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_profile_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
