# Generated by Django 4.2.7 on 2024-01-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_student_profile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remark',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Conditional', 'Conditional'), ('Failed', 'Failed')], max_length=25),
        ),
    ]
