# Generated by Django 4.2.7 on 2024-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_schedule_room_alter_grade_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
