# Generated by Django 4.2.7 on 2024-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_subject_subject_code_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
    ]
