# Generated by Django 4.2.7 on 2024-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='webapp.subject'),
        ),
    ]
