# Generated by Django 4.2.7 on 2024-01-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_schedule_subject_schedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('LAB', 'Laboratory'), ('LEC', 'Lecture')], max_length=10),
        ),
    ]
